### PR TITLE
Adding the icon

### PR DESCRIPTION
**Pull request by aarongustafson**

### CODE REVIEW

**Comment by aarongustafson** [comment]
Check it

**Review by jevery23 — COMMENTED** [review]
Looks good, need at least the image sizes given for page action and settings menu icons respectively. Couple things though:
1. The 2 SVG files are the same it seems, we should just have the one.
2. Please remove some of the icons we do not use, fine to keep icons like the 20, 25 (may need later) and the ones we are using but the others I think can be removed, unless there is some unknown good reason to keep them.

**Comment by aarongustafson** [comment]
I removed everything but the reference icons (from which we’d make others).

I also updated the name as we seem to prefer Seeing UI.

**Review by jevery23 — COMMENTED** [review]
Looks good, only thing is that I would have expected icon file to be a .ai file rather than a .psd file.

**Pull request merged**
